version: "3.9"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5499:5432"
    volumes:
      - reactive_data:/var/lib/postgresql/data
volumes:
  reactive_data: